baseURL = "https://ameertaweel.github.io"
languageCode = "en-us"
title = "Ameer Taweel"
theme = "hugo-coder"

[params]

author = "Ameer Taweel"
info = "Computer Engineer That Writes Code For Fun"
description = "Ameer Taweel's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"

favicon_16 = "images/favicon-16x16.png"
favicon_32 = "images/favicon-32x32.png"

since = 2022

colorScheme = "dark"
hidecolorschemetoggle = false

[[params.social]]
name = "GitHub"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Ameer Taweel/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/ameer-taweel/"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 3
url = "mailto:ameertaweel2002@gmail.com"

[[params.social]]
name = "Dotfiles"
icon = "fa fa-2x fa-gear"
weight = 4
url = "https://github.com/AmeerTaweel/dotfiles"

[[menu.main]]
name = "Projects"
weight = 1
url = "projects/"

[[menu.main]]
name = "Certificates"
weight = 2
url = "certificates/"
