baseURL = "https://ameertaweel.github.io"
languageCode = "en-us"
title = "Ameer Taweel"
subtitle = "TODO"
theme = "hugo-coder"

[params]

author = "Ameer Taweel"
info = "IComputer Engineer That Writes Code For Fun"
description = "John Doe's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"

# favicon_32 = "/img/favicon-32x32.png"
# favicon_16 = "/img/favicon-16x16.png"

since = 2022

colorScheme = "dark"
hidecolorschemetoggle = false

[[params.social]]
name = "GitHub"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Ameer Taweel/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/ameer-taweel/"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 3
url = "mailto:ameertaweel2002@gmail.com"
